#************************** MDIS4 device descriptor *************************
#
# m43_min.dsc: Descriptor for M43
# Automatically generated by mdiswiz 0.95-linux-0 from 13m04306.xml
# 2003-06-05
#
#************************** MDIS4 device descriptor *************************

M43_1 {
        #------------------------------------------------------------------------
        #       general parameters (don't modify)
        #------------------------------------------------------------------------
    DESC_TYPE = U_INT32 0x1
    HW_TYPE = STRING M43
        #------------------------------------------------------------------------
        #       reference to base board
        #------------------------------------------------------------------------
    BOARD_NAME = STRING A201_1
    DEVICE_SLOT = U_INT32 0x0
}
# EOF
