#************************** MDIS4 device descriptor *************************
#
# m43_max.dsc: Descriptor for M43
# Automatically generated by mdiswiz 0.95-linux-0 from 13m04306.xml
# 2003-06-05
#
#****************************************************************************

M43_1 {
        #------------------------------------------------------------------------
        #       general parameters (don't modify)
        #------------------------------------------------------------------------
    DESC_TYPE = U_INT32 0x1
    HW_TYPE = STRING M43

        #------------------------------------------------------------------------
        #       reference to base board
        #------------------------------------------------------------------------
    BOARD_NAME = STRING A201_1
    DEVICE_SLOT = U_INT32 0x0

        #------------------------------------------------------------------------
        #       device parameters
        #------------------------------------------------------------------------
    # Define wether M-Module ID-PROM is checked
    # 0 := disable -- ignore IDPROM
    # 1 := enable
    ID_CHECK = U_INT32 1

        #------------------------------------------------------------------------
        #       debug levels (optional)
        #   this keys have only effect on debug drivers
        #------------------------------------------------------------------------
    DEBUG_LEVEL = U_INT32 0xc0008000
    DEBUG_LEVEL_MK = U_INT32 0xc0008000
    DEBUG_LEVEL_OSS = U_INT32 0xc0008000
    DEBUG_LEVEL_DESC = U_INT32 0xc0008000
}
# EOF
