#
#	Makefile for linux native MDIS example
#

CC			= gcc
LD			= ld
CFLAGS		= -Wall -DLINUX -I/opt/menlinux/INCLUDE/COM \
							-I/opt/menlinux/INCLUDE/NATIVE
LDFLAGS  	= -lmdis_api


mdis_native_ex: mdis_native_ex.o


